### ISSUE TITLE
400 from googleapis.com

### ISSUE THREAD

**Issue by elsehow** [coloringchaos/daylight-chrome#2]
after installing from the app store, the clock seems to be stuck at 0 deg. in the developer console I see this error

```
PositionError {code: 2, message: "Network location provider at 'https://www.googleapis.com/' : Returned error code 400."}
```

**Comment by coloringchaos** [comment]
This is the error that results if the page is attempting to get the user's location via an insecure connection (http rather than https). It's strange because as a chrome extension the issue of hosting on a secure server should be bypassed..

When you download the extension I believe you need to agree to allowing it to connect to your location - is it possible that you said 'no'? 

I will look into this further...

**Comment by elsehow** [comment]
I get the icon in chrome's location bar notifying me that the page is tracking my location. Let me know how I can help!

**Comment by elsehow** [comment]
update: I get this error in chromium, but the clock works fine in chrome! my bad
